/* 
 * API Rejestr WL
 *
 * Rejestr Podatników VAT
 *
 * OpenAPI spec version: 1.6.0
 * Contact: WykazPodatnikow@mf.gov.pl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = MFApiService.Client.SwaggerDateConverter;

namespace MFApiService.Model
{
    /// <summary>
    /// EntryError
    /// </summary>
    [DataContract]
    public partial class EntryError : IEquatable<EntryError>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EntryError" /> class.
        /// </summary>
        /// <param name="identifier">Przekazany identyfikator (Nip, Regon, Numer rachunku bankowego)  (required).</param>
        /// <param name="error">error (required).</param>
        public EntryError(string identifier = default, Exception error = default)
        {
            // to ensure "identifier" is required (not null)
            if (identifier == null)
            {
                throw new InvalidDataException("identifier is a required property for EntryError and cannot be null");
            }
            else
            {
                Identifier = identifier;
            }
            // to ensure "error" is required (not null)
            if (error == null)
            {
                throw new InvalidDataException("error is a required property for EntryError and cannot be null");
            }
            else
            {
                Error = error;
            }
        }

        /// <summary>
        /// Przekazany identyfikator (Nip, Regon, Numer rachunku bankowego) 
        /// </summary>
        /// <value>Przekazany identyfikator (Nip, Regon, Numer rachunku bankowego) </value>
        [DataMember(Name = "identifier", EmitDefaultValue = false)]
        public string Identifier { get; set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [DataMember(Name = "error", EmitDefaultValue = false)]
        public Exception Error { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EntryError {\n");
            sb.Append("  Identifier: ").Append(Identifier).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as EntryError);
        }

        /// <summary>
        /// Returns true if EntryError instances are equal
        /// </summary>
        /// <param name="input">Instance of EntryError to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EntryError input)
        {
            if (input == null)
                return false;

            return
                (
                    Identifier == input.Identifier ||
                    Identifier != null &&
                    Identifier.Equals(input.Identifier)
                ) &&
                (
                    Error == input.Error ||
                    Error != null &&
                    Error.Equals(input.Error)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Identifier != null)
                    hashCode = hashCode * 59 + Identifier.GetHashCode();
                if (Error != null)
                    hashCode = hashCode * 59 + Error.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
