// <auto-generated />
using System;
using BIRBlazorTest.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BIRBlazorTest.Migrations
{
    [DbContext(typeof(CompanyDBContext))]
    [Migration("20220625075304_Initial-Commit")]
    partial class InitialCommit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("BIRBlazorTest.Models.CompanyModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Regon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("BIRService.Models.ErrorModel", b =>
                {
                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CompanyModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessageEn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessagePl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ErrorCode");

                    b.HasIndex("CompanyModelId");

                    b.ToTable("ErrorModel");
                });

            modelBuilder.Entity("BIRService.Models.ErrorModel", b =>
                {
                    b.HasOne("BIRBlazorTest.Models.CompanyModel", null)
                        .WithMany("Errors")
                        .HasForeignKey("CompanyModelId");
                });

            modelBuilder.Entity("BIRBlazorTest.Models.CompanyModel", b =>
                {
                    b.Navigation("Errors");
                });
#pragma warning restore 612, 618
        }
    }
}
